// Mock employee data
const employees = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    department: "Engineering",
    position: "Senior Developer",
    salary: 85000,
    hire_date: "2021-03-15",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 2,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    phone: "123-456-7891",
    department: "Marketing",
    position: "Marketing Manager",
    salary: 78000,
    hire_date: "2021-05-20",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 3,
    first_name: "Michael",
    last_name: "Johnson",
    email: "michael.johnson@example.com",
    phone: "123-456-7892",
    department: "Finance",
    position: "Financial Analyst",
    salary: 72000,
    hire_date: "2021-07-10",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 4,
    first_name: "Emily",
    last_name: "Williams",
    email: "emily.williams@example.com",
    phone: "123-456-7893",
    department: "Human Resources",
    position: "HR Specialist",
    salary: 65000,
    hire_date: "2021-09-05",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 5,
    first_name: "David",
    last_name: "Brown",
    email: "david.brown@example.com",
    phone: "123-456-7894",
    department: "Engineering",
    position: "Frontend Developer",
    salary: 70000,
    hire_date: "2022-01-15",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: 6,
    first_name: "Sarah",
    last_name: "Miller",
    email: "sarah.miller@example.com",
    phone: "123-456-7895",
    department: "Sales",
    position: "Sales Representative",
    salary: 68000,
    hire_date: "2022-03-10",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 7,
    first_name: "James",
    last_name: "Wilson",
    email: "james.wilson@example.com",
    phone: "123-456-7896",
    department: "Engineering",
    position: "Backend Developer",
    salary: 72000,
    hire_date: "2022-05-20",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: 8,
    first_name: "Jennifer",
    last_name: "Taylor",
    email: "jennifer.taylor@example.com",
    phone: "123-456-7897",
    department: "Marketing",
    position: "Content Specialist",
    salary: 62000,
    hire_date: "2022-07-15",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: 9,
    first_name: "Robert",
    last_name: "Anderson",
    email: "robert.anderson@example.com",
    phone: "123-456-7898",
    department: "Finance",
    position: "Accountant",
    salary: 67000,
    hire_date: "2022-09-10",
    status: "on_leave",
    profile_image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: 10,
    first_name: "Lisa",
    last_name: "Thomas",
    email: "lisa.thomas@example.com",
    phone: "123-456-7899",
    department: "Customer Support",
    position: "Support Specialist",
    salary: 58000,
    hire_date: "2022-11-05",
    status: "active",
    profile_image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
];

export default employees;
