// Mock leave data
const leaves = [
  {
    id: 1,
    employee_id: 1,
    employee_name: "John Doe",
    leave_type: "Annual Leave",
    start_date: "2023-06-10",
    end_date: "2023-06-15",
    days: 6,
    reason: "Family vacation",
    status: "approved",
    created_at: "2023-05-20T10:30:00Z",
  },
  {
    id: 2,
    employee_id: 3,
    employee_name: "Michael Johnson",
    leave_type: "Sick Leave",
    start_date: "2023-07-05",
    end_date: "2023-07-07",
    days: 3,
    reason: "Flu",
    status: "approved",
    created_at: "2023-07-04T08:15:00Z",
  },
  {
    id: 3,
    employee_id: 5,
    employee_name: "David Brown",
    leave_type: "Personal Leave",
    start_date: "2023-07-20",
    end_date: "2023-07-21",
    days: 2,
    reason: "Personal matters",
    status: "approved",
    created_at: "2023-07-10T14:20:00Z",
  },
  {
    id: 4,
    employee_id: 7,
    employee_name: "James Wilson",
    leave_type: "Annual Leave",
    start_date: "2023-08-01",
    end_date: "2023-08-10",
    days: 10,
    reason: "Summer vacation",
    status: "pending",
    created_at: "2023-07-15T11:45:00Z",
  },
  {
    id: 5,
    employee_id: 9,
    employee_name: "Robert Anderson",
    leave_type: "Sick Leave",
    start_date: "2023-07-25",
    end_date: "2023-08-15",
    days: 22,
    reason: "Surgery recovery",
    status: "approved",
    created_at: "2023-07-20T09:30:00Z",
  },
  {
    id: 6,
    employee_id: 2,
    employee_name: "Jane Smith",
    leave_type: "Annual Leave",
    start_date: "2023-09-05",
    end_date: "2023-09-10",
    days: 6,
    reason: "Family event",
    status: "pending",
    created_at: "2023-08-20T16:10:00Z",
  },
  {
    id: 7,
    employee_id: 4,
    employee_name: "Emily Williams",
    leave_type: "Personal Leave",
    start_date: "2023-08-25",
    end_date: "2023-08-25",
    days: 1,
    reason: "Doctor appointment",
    status: "approved",
    created_at: "2023-08-20T10:00:00Z",
  },
  {
    id: 8,
    employee_id: 6,
    employee_name: "Sarah Miller",
    leave_type: "Annual Leave",
    start_date: "2023-10-15",
    end_date: "2023-10-20",
    days: 6,
    reason: "Vacation",
    status: "pending",
    created_at: "2023-09-25T13:20:00Z",
  },
  {
    id: 9,
    employee_id: 8,
    employee_name: "Jennifer Taylor",
    leave_type: "Sick Leave",
    start_date: "2023-08-05",
    end_date: "2023-08-06",
    days: 2,
    reason: "Not feeling well",
    status: "approved",
    created_at: "2023-08-04T17:30:00Z",
  },
  {
    id: 10,
    employee_id: 10,
    employee_name: "Lisa Thomas",
    leave_type: "Annual Leave",
    start_date: "2023-11-01",
    end_date: "2023-11-05",
    days: 5,
    reason: "Personal trip",
    status: "pending",
    created_at: "2023-10-15T09:45:00Z",
  },
];

// Leave types
const leaveTypes = [
  {
    id: 1,
    name: "Annual Leave",
    description: "Regular vacation leave",
    max_days: 20,
  },
  {
    id: 2,
    name: "Sick Leave",
    description: "Leave for medical reasons",
    max_days: 10,
  },
  {
    id: 3,
    name: "Personal Leave",
    description: "Leave for personal matters",
    max_days: 5,
  },
  {
    id: 4,
    name: "Maternity Leave",
    description: "Leave for childbirth and recovery",
    max_days: 90,
  },
  {
    id: 5,
    name: "Paternity Leave",
    description: "Leave for new fathers",
    max_days: 5,
  },
];

// Leave balances
const leaveBalances = [
  {
    id: 1,
    employee_id: 1,
    leave_type_id: 1,
    leave_type: "Annual Leave",
    total_days: 20,
    used_days: 6,
    year: 2023,
  },
  {
    id: 2,
    employee_id: 1,
    leave_type_id: 2,
    leave_type: "Sick Leave",
    total_days: 10,
    used_days: 0,
    year: 2023,
  },
  {
    id: 3,
    employee_id: 1,
    leave_type_id: 3,
    leave_type: "Personal Leave",
    total_days: 5,
    used_days: 0,
    year: 2023,
  },
  {
    id: 4,
    employee_id: 2,
    leave_type_id: 1,
    leave_type: "Annual Leave",
    total_days: 20,
    used_days: 0,
    year: 2023,
  },
  {
    id: 5,
    employee_id: 2,
    leave_type_id: 2,
    leave_type: "Sick Leave",
    total_days: 10,
    used_days: 2,
    year: 2023,
  },
];

export { leaves, leaveTypes, leaveBalances };
