// Mock performance review data
const performanceReviews = [
  {
    id: 1,
    employee_id: 1,
    employee_name: "John Doe",
    reviewer_id: 3,
    reviewer_name: "Manager User",
    review_period_start: "2023-01-01",
    review_period_end: "2023-06-30",
    status: "completed",
    overall_rating: 4.5,
    strengths:
      "Excellent technical skills, great team player, proactive problem solver",
    weaknesses: "Could improve documentation practices",
    comments:
      "John has been an outstanding performer this period. His contributions to the project X were significant.",
    next_review_date: "2023-12-31",
    created_at: "2023-07-15T10:00:00Z",
    updated_at: "2023-07-20T14:30:00Z",
  },
  {
    id: 2,
    employee_id: 2,
    employee_name: "Jane Smith",
    reviewer_id: 3,
    reviewer_name: "Manager User",
    review_period_start: "2023-01-01",
    review_period_end: "2023-06-30",
    status: "completed",
    overall_rating: 4.2,
    strengths:
      "Strong communication skills, excellent client management, good at meeting deadlines",
    weaknesses: "Could delegate more tasks to team members",
    comments:
      "Jane has shown great leadership in the marketing campaign. Her strategic thinking has helped increase our market presence.",
    next_review_date: "2023-12-31",
    created_at: "2023-07-16T11:00:00Z",
    updated_at: "2023-07-21T15:30:00Z",
  },
  {
    id: 3,
    employee_id: 3,
    employee_name: "Michael Johnson",
    reviewer_id: 3,
    reviewer_name: "Manager User",
    review_period_start: "2023-01-01",
    review_period_end: "2023-06-30",
    status: "completed",
    overall_rating: 3.8,
    strengths: "Detail-oriented, thorough analysis, reliable",
    weaknesses:
      "Could improve presentation skills, sometimes misses the bigger picture",
    comments:
      "Michael has been consistent in his performance. His financial analyses are always accurate and timely.",
    next_review_date: "2023-12-31",
    created_at: "2023-07-17T09:30:00Z",
    updated_at: "2023-07-22T13:45:00Z",
  },
  {
    id: 4,
    employee_id: 4,
    employee_name: "Emily Williams",
    reviewer_id: 2,
    reviewer_name: "HR Manager",
    review_period_start: "2023-01-01",
    review_period_end: "2023-06-30",
    status: "completed",
    overall_rating: 4.0,
    strengths:
      "Excellent interpersonal skills, good at conflict resolution, organized",
    weaknesses: "Could improve on technical HR knowledge",
    comments:
      "Emily has been a great addition to the HR team. Her people skills have helped resolve several internal issues.",
    next_review_date: "2023-12-31",
    created_at: "2023-07-18T10:15:00Z",
    updated_at: "2023-07-23T16:00:00Z",
  },
  {
    id: 5,
    employee_id: 5,
    employee_name: "David Brown",
    reviewer_id: 3,
    reviewer_name: "Manager User",
    review_period_start: "2023-01-01",
    review_period_end: "2023-06-30",
    status: "in_progress",
    overall_rating: null,
    strengths: "",
    weaknesses: "",
    comments: "",
    next_review_date: null,
    created_at: "2023-07-25T09:00:00Z",
    updated_at: "2023-07-25T09:00:00Z",
  },
];

// Performance goals
const performanceGoals = [
  {
    id: 1,
    review_id: 1,
    description: "Complete advanced React certification",
    target: "By September 2023",
    achievement: "Completed in August 2023",
    rating: 5.0,
  },
  {
    id: 2,
    review_id: 1,
    description: "Mentor junior developers",
    target: "Mentor at least 2 junior developers",
    achievement: "Mentored 3 junior developers",
    rating: 5.0,
  },
  {
    id: 3,
    review_id: 1,
    description: "Improve code documentation",
    target: "Document all new code according to team standards",
    achievement: "Documentation improved but still some gaps",
    rating: 3.5,
  },
  {
    id: 4,
    review_id: 2,
    description: "Increase social media engagement",
    target: "20% increase in engagement",
    achievement: "25% increase achieved",
    rating: 5.0,
  },
  {
    id: 5,
    review_id: 2,
    description: "Launch new marketing campaign",
    target: "Q2 2023",
    achievement: "Launched in May 2023",
    rating: 4.0,
  },
  {
    id: 6,
    review_id: 3,
    description: "Reduce financial reporting time",
    target: "Reduce by 20%",
    achievement: "Reduced by 15%",
    rating: 3.5,
  },
  {
    id: 7,
    review_id: 3,
    description: "Implement new financial analysis tool",
    target: "By June 2023",
    achievement: "Implemented in June 2023",
    rating: 4.0,
  },
  {
    id: 8,
    review_id: 4,
    description: "Improve employee onboarding process",
    target: "Reduce onboarding time by 30%",
    achievement: "Reduced by 35%",
    rating: 5.0,
  },
  {
    id: 9,
    review_id: 4,
    description: "Conduct employee satisfaction survey",
    target: "Q2 2023",
    achievement: "Completed in May 2023",
    rating: 4.0,
  },
  {
    id: 10,
    review_id: 4,
    description: "Update HR policies",
    target: "By June 2023",
    achievement: "Completed in July 2023 (slight delay)",
    rating: 3.0,
  },
];

export { performanceReviews, performanceGoals };
