// Mock user data for frontend authentication
const users = [
  {
    id: 1,
    username: "admin",
    email: "admin@example.com",
    password: "password123",
    role: "admin",
    first_name: "Admin",
    last_name: "User",
    department: "Administration",
    position: "System Administrator",
    phone: "123-456-7890",
    hire_date: "2022-01-01",
    profile_image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    username: "hr",
    email: "hr@example.com",
    password: "password123",
    role: "hr",
    first_name: "HR",
    last_name: "Manager",
    department: "Human Resources",
    position: "HR Manager",
    phone: "123-456-7891",
    hire_date: "2022-01-15",
    profile_image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    username: "manager",
    email: "manager@example.com",
    password: "password123",
    role: "manager",
    first_name: "Department",
    last_name: "Manager",
    department: "Engineering",
    position: "Engineering Manager",
    phone: "123-456-7892",
    hire_date: "2022-02-01",
    profile_image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    username: "employee",
    email: "employee@example.com",
    password: "password123",
    role: "employee",
    first_name: "Regular",
    last_name: "Employee",
    department: "Engineering",
    position: "Software Developer",
    phone: "123-456-7893",
    hire_date: "2022-03-15",
    profile_image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
];

export default users;
